name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node version to match your project requirements

      - name: Installing dependencies
        run: npm install    

      - name: Run tests
        run: npm run test  # Assumes you have tests configured in your package.json

      - name: final step
        if: success()
        run: npm run dev    
                







